// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiLX-okW4yyN5x05WqzltrRkkW7PvnDxk',
    appId: '1:708892247921:web:11215fefd7dd53672898d0',
    messagingSenderId: '708892247921',
    projectId: 'webullish-14c86',
    authDomain: 'webullish-14c86.firebaseapp.com',
    storageBucket: 'webullish-14c86.appspot.com',
    measurementId: 'G-KQD9Q31B22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbBh0q-IBQg0EryLYonwsP24iH4G6qh9U',
    appId: '1:708892247921:android:e9e2b999a7e537f82898d0',
    messagingSenderId: '708892247921',
    projectId: 'webullish-14c86',
    storageBucket: 'webullish-14c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsSQ8rVnfen7kB5nPWrsEfP0fPdU8yUI',
    appId: '1:708892247921:ios:a791500d6aebd6682898d0',
    messagingSenderId: '708892247921',
    projectId: 'webullish-14c86',
    storageBucket: 'webullish-14c86.appspot.com',
    iosClientId: '708892247921-s8sb06in85s9pe8k6rnl7tg3i2lucnpk.apps.googleusercontent.com',
    iosBundleId: 'com.webullish.webullish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsSQ8rVnfen7kB5nPWrsEfP0fPdU8yUI',
    appId: '1:708892247921:ios:a791500d6aebd6682898d0',
    messagingSenderId: '708892247921',
    projectId: 'webullish-14c86',
    storageBucket: 'webullish-14c86.appspot.com',
    iosClientId: '708892247921-s8sb06in85s9pe8k6rnl7tg3i2lucnpk.apps.googleusercontent.com',
    iosBundleId: 'com.webullish.webullish',
  );
}
